### PR TITLE
Added support for periodic breaks

### PR DESCRIPTION
**Pull request by ashmind**
Really appreciate your timer — we use it all the time.

However we noticed that we often forget to make breaks (to grab tea/check Slack/etc) while mobbing.
It felt like an automation opportunity, so I added that to the timer.

agility-breaks-settings

agility-breaks-timer

### CODE REVIEW

**Comment by jahed** [comment]
Thanks for the PR.

Have you considered adding a "Break" mobster instead? That's how we remember to take breaks at @Unruly. So once everyone's had a go, we take a break. We've found it a lot simpler than scheduling breaks out-of-cycle from the regular rotation period.

I'm saying this as one of my concerns right now with this app is the growing complexity, I'll need to start thinking about automated tests.

**Comment by ashmind** [comment]
@jahed Thanks — I've considered that, but it doesn't quite match the timescales.
E.g. we often have just two people, and 10 mins break every 20 mins would be too much.

I can try to add tests though — what framework do you prefer?
I can take a look tomorrow (in 16 hrs or so).

**Comment by jahed** [comment]
@ashmind 

It's worth bearing in mind that right now, thanks to the Netlify move (in #7), your changes are available here:

https://5a895bb992226a5048534e69--agility.netlify.com/

I'll get round to manually testing it next week and if it's okay, I'll merge the PR (provided the remainder of #7 is done by then). You can also use it to make sure the new feature is working correctly in the long run.

## Automated Testing 

In terms of automated testing, there are a few things to consider first:

- Automated deploys. Right now Netlify isn't configured to run tests when it builds the app. If tests fail, it'll still deploy a potentially broken app. I'll fix this as part of #7.
- Acceptance tests (aka end-to-end browser tests). Having a build server run these will be difficult as far as I know without some sort of BrowserStack/Saucelabs integration. Travis apparently supports headless modes so I might give that a try. If it can be done entirely in Netlify, that would be ideal.

https://docs.travis-ci.com/user/gui-and-headless-browsers/

I'll do some initial research and share in a separate issue ticket. Chances are, the test framework will be Nightwatch since that's what I'm already familiar with.

https://github.com/nightwatchjs/nightwatch

**Comment by jahed** [comment]
I gave this a try. There's two issues with it:

- If the break time isn't divisible the rotation time, it's confusing. Though, it rounds to the next rotation so it doesn't error, but the outcome might not be what some might assume.
- It adds more options for the user to decide on, affecting the simplicity.

There's a workaround for 10minute pairs that want a break every 60 minutes: Add 6 mobsters, cycling each person 3 times then add a break. It's not great but IMO better than adding more controls for a feature maybe only a handful of people need. Until more people ask for it, I'm not going to merge this. Again, worth saying that it's still available here:

https://5a895bb992226a5048534e69--agility.netlify.com/

Thanks again for the PR, @ashmind. I'm planning to redesign the timer -- probably as a separate app -- and I will take features like this into account so that it's more elegant. And, more importantly, it'll have tests!

**Pull request closed without merging**
